name: Container build & push jobs

on:
  push:
    branches:
      - master
    tags:
      - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/

jobs:
  build_push_container:
    runs-on: ubuntu-latest
    name: Build and push the container image for a commit or tag.
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.14.x

      - name: Cache for Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache for Docker's buildx
        uses: actions/cache@v3
        with:
          path: .buildxcache/
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/*.go', 'Dockerfile', 'go.sum') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Snapshot container buid & push
        run: make conditional-container-build-push

      - name: Release container build & push
        if: startsWith(github.ref, 'refs/tags/v')
        run: make container-release-build-push
