name: Go code jobs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  source_lint:
    runs-on: ubuntu-latest
    name: Linting Go code.
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.14.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run source code linting.
        run: make lint

  go_build_and_test:
    runs-on: ubuntu-latest
    name: Build the Go Binary and run tests.
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build the Go binary.
        run: make token-refresher

      - name: Check if repo is dirty.
        run: git diff --exit-code

      - name: Run the tests.
        run: make test

  build_jsonnet:
    runs-on: ubuntu-latest
    name: Build jsonnet files.
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run source code linting.
        run: make manifests

      - name: Check if repo is dirty.
        run: git diff --exit-code
